/** Admin navigator tree — mirrors admin.html */
export const adminNav = [
  {
    label: "Servers",
    icon: "servers",
    indent: 0,
    open: true,
    children: [
      {
        label: "MetaTrader Server",
        icon: "server",
        indent: 1,
        open: true,
        children: [
          { label: "Network Cluster", icon: "network-cluster", indent: 2, disabled: true },
          { label: "Integrations", icon: "integrations", indent: 2, disabled: true },
          { label: "Automations", icon: "automations", indent: 2, disabled: true },
          { label: "Security", icon: "security", indent: 2, disabled: true },
          { moduleId: "time", label: "Time", icon: "time", indent: 2 },
          { moduleId: "holidays", label: "Holidays", icon: "holidays", indent: 2 },
          { moduleId: "leverages", label: "Leverages", icon: "leverages", indent: 2 },
          { moduleId: "groups", label: "Groups", icon: "groups", indent: 2, count: "(39)" },
          {
            label: "Clients & Accounts",
            icon: "clients-accounts",
            indent: 2,
            open: true,
            children: [
              { moduleId: "clients", label: "Clients", icon: "clients-tree", indent: 3, count: "(4)" },
              { moduleId: "managers", label: "Managers", icon: "managers-tree", indent: 3, count: "(3)" },
              { moduleId: "users", label: "Trading Accounts", icon: "accounts-tree", indent: 3, count: "(5)" },
            ],
          },
          {
            label: "Orders & Deals",
            icon: "orders-deals",
            indent: 2,
            open: true,
            children: [
              { moduleId: "positions", label: "Positions", icon: "positions", indent: 3, count: "(3)" },
              { moduleId: "orders", label: "Orders", icon: "orders-tree", indent: 3, count: "(4)" },
              { moduleId: "deals", label: "Deals", icon: "deals-tree", indent: 3, count: "(4)" },
            ],
          },
          { label: "Payments", icon: "payments", indent: 2, disabled: true },
          { label: "Gateways", icon: "gateways", indent: 2, disabled: true },
          { moduleId: "datafeeds", label: "Data Feeds", icon: "datafeeds", indent: 2 },
          { label: "Plugins", icon: "plugins", indent: 2, disabled: true },
          { label: "Reports", icon: "reports", indent: 2, disabled: true },
          { moduleId: "routing", label: "Routing", icon: "routing", indent: 2 },
          { moduleId: "symbols", label: "Symbols", icon: "symbols-tree", indent: 2, count: "(160)" },
          { label: "Spreads", icon: "spreads", indent: 2, disabled: true },
          { label: "Charts & Ticks", icon: "charts-ticks", indent: 2, disabled: true },
          { label: "Subscriptions", icon: "subscriptions", indent: 2, disabled: true },
          { label: "Mailbox", icon: "mailbox", indent: 2, disabled: true, count: "(0)" },
        ],
      },
    ],
  },
  { label: "Support Center", icon: "support-center", indent: 0, disabled: true },
];
