import { fmtTs } from "../../../lib/formatters.js";
import {
  clientColumns,
  groupColumns,
  managerRoleIconCol,
  tsCol,
  userColumns,
} from "../columns/shared.js";
import {
  adminDealCols,
  adminOrderCols,
  adminPositionCols,
} from "../columns/trade.js";

/** @type {Record<string, import('../registry.js').ModuleDef>} */
export const adminModules = {
  time: {
    type: "settings",
    title: "Time",
    settingsId: "time",
  },
  holidays: {
    type: "list",
    title: "Holidays",
    endpoint: "/api/v1/holidays",
    query: { limit: "500" },
    idKey: "holiday_id",
    searchPlaceholder: "Description…",
    columns: [
      { key: "holiday_id", label: "ID" },
      {
        key: "date",
        label: "Date",
        render: (r) => {
          const y = r.year ? r.year : "****";
          return `${y}.${String(r.month).padStart(2, "0")}.${String(r.day).padStart(2, "0")}`;
        },
      },
      { key: "from", label: "From" },
      { key: "to", label: "To" },
      { key: "mode", label: "Mode" },
      { key: "description", label: "Description" },
      {
        key: "symbols",
        label: "Symbols",
        render: (r) => (r.symbols || []).join(", "),
      },
    ],
  },
  leverages: {
    type: "list",
    title: "Leverage profiles",
    endpoint: "/api/v1/leverage-profiles",
    query: { limit: "500" },
    idKey: "leverage_id",
    searchPlaceholder: "Profile name…",
    columns: [
      { key: "leverage_id", label: "ID" },
      { key: "name", label: "Name" },
      { key: "flags", label: "Flags" },
      tsCol("timestamp", "Updated"),
    ],
  },
  groups: {
    type: "list",
    title: "Groups",
    endpoint: "/api/v1/groups",
    query: { flat: "1", limit: "500" },
    idKey: "group_id",
    pathKey: "group",
    editLabel: "✎ Group Settings…",
    legacyDetail: "groups-config.html",
    searchPlaceholder: "Group name…",
    note:
      "<strong>Group</strong> = trading template (margin, symbols, permissions). Trading accounts are assigned to a group path e.g. <code>real\\standard</code>. Double-click or <strong>Group Settings</strong> for full config.",
    columns: groupColumns({ extended: true }),
  },
  clients: {
    type: "list",
    title: "Clients",
    endpoint: "/api/v1/clients",
    query: { limit: "500" },
    idKey: "client_id",
    editLabel: "✎ Client profile…",
    legacyDetail: "clients-detail.html",
    searchPlaceholder: "Name, email…",
    note:
      "<strong>Client</strong> = CRM identity. Each client owns trading accounts (logins) in a group. Double-click to open profile.",
    columns: clientColumns("admin", { extended: true }),
  },
  managers: {
    type: "list",
    title: "Managers",
    endpoint: "/api/v1/managers",
    query: { limit: "500" },
    idKey: "login",
    editLabel: "✎ Manager profile…",
    legacyDetail: "managers-detail.html",
    detailParam: "login",
    columns: [
      managerRoleIconCol(),
      { key: "login", label: "Login" },
      { key: "name", label: "Name" },
      {
        key: "mailbox",
        label: "Mailbox",
        render: (r) => r.mailbox || "—",
      },
      {
        key: "groups",
        label: "Groups",
        render: (r) => (r.groups || []).join(", "),
      },
      {
        key: "type",
        label: "Type",
        render: (r) => (r.rights?.right_admin ? "Administrator" : "Manager"),
      },
    ],
  },
  users: {
    type: "list",
    title: "Trading accounts",
    endpoint: "/api/v1/users",
    query: { limit: "500" },
    idKey: "login",
    editLabel: "✎ Account profile…",
    legacyDetail: "users-detail.html",
    detailParam: "login",
    columns: userColumns("admin", { extended: true }),
  },
  positions: {
    type: "list",
    title: "Positions",
    endpoint: "/api/v1/positions",
    query: { limit: "500" },
    idKey: "position_id",
    editLabel: "✎ Position detail…",
    legacyDetail: "positions-detail.html",
    columns: adminPositionCols(),
  },
  orders: {
    type: "list",
    title: "Orders",
    endpoint: "/api/v1/orders",
    query: { limit: "500", active: "false" },
    idKey: "order_id",
    editLabel: "✎ Order detail…",
    legacyDetail: "orders-detail.html",
    columns: adminOrderCols(),
  },
  deals: {
    type: "list",
    title: "Deals",
    endpoint: "/api/v1/deals",
    query: { limit: "500" },
    idKey: "deal_id",
    editLabel: "✎ Deal detail…",
    legacyDetail: "deals-detail.html",
    columns: adminDealCols(),
  },
  datafeeds: {
    type: "split",
    title: "Data feeds",
    endpoint: "/api/v1/datafeeds",
    query: { limit: "500" },
    idKey: "datafeed_id",
    editLabel: "✎ Data Feed Settings…",
    detailKind: "datafeed",
    searchPlaceholder: "Name, module, server…",
    note:
      "Data feeds supply quotes, market depth, and news to the history server. List order defines priority.",
  },
  routing: {
    type: "list",
    title: "Routing",
    endpoint: "/api/v1/routing",
    query: { limit: "500" },
    idKey: "routing_id",
    editLabel: "✎ Rule Settings…",
    legacyDetail: "routing-config.html",
    searchPlaceholder: "Rule name…",
    columns: [
      { key: "routing_id", label: "#" },
      { key: "name", label: "Name" },
      { key: "mode", label: "Mode" },
      { key: "action", label: "Action" },
      { key: "routing_index", label: "Index" },
      tsCol("date_modified", "Modified"),
    ],
  },
  symbols: {
    type: "split",
    title: "Symbols",
    endpoint: "/api/v1/symbols",
    query: { limit: "500" },
    idKey: "symbol_id",
    editLabel: "✎ Symbol Settings…",
    detailKind: "symbol",
    searchPlaceholder: "Symbol, path, description…",
  },
};
