import { clientColumns, groupColumns, tsCol, userColumns } from "../columns/shared.js";
import { managerTradeCols } from "../columns/trade.js";

/** @type {Record<string, import('../registry.js').ModuleDef>} */
export const managerModules = {
  users: {
    type: "list",
    title: "Trading Accounts",
    endpoint: "/api/v1/users",
    query: { limit: "500" },
    idKey: "login",
    editLabel: "✎ Account profile…",
    legacyDetail: "users-detail.html",
    detailParam: "login",
    columns: userColumns("manager"),
  },
  clients: {
    type: "list",
    title: "Clients",
    endpoint: "/api/v1/clients",
    query: { limit: "500" },
    idKey: "client_id",
    editLabel: "✎ Client profile…",
    legacyDetail: "clients-detail.html",
    searchPlaceholder: "Name, email…",
    columns: clientColumns("manager"),
  },
  positions: {
    type: "list",
    title: "Positions",
    endpoint: "/api/v1/positions",
    query: { limit: "500" },
    idKey: "position_id",
    legacyDetail: "positions-detail.html",
    legacyDetailPanel: "admin",
    columns: managerTradeCols("positions", "manager"),
  },
  orders: {
    type: "list",
    title: "Orders",
    endpoint: "/api/v1/orders",
    query: { limit: "500" },
    idKey: "order_id",
    legacyDetail: "orders-detail.html",
    legacyDetailPanel: "admin",
    note:
      "Orders belong to a trading account (<strong>login</strong>). Click login to open the account with its full trade history.",
    columns: managerTradeCols("orders", "manager"),
  },
  deals: {
    type: "list",
    title: "Deals",
    endpoint: "/api/v1/deals",
    query: { limit: "500" },
    idKey: "deal_id",
    legacyDetail: "deals-detail.html",
    legacyDetailPanel: "admin",
    columns: managerTradeCols("deals", "manager"),
  },
  dealing: {
    type: "list",
    title: "Dealing queue",
    endpoint: "/api/v1/dealing",
    idKey: "order_id",
    search: false,
    columns: [
      { key: "order_id", label: "Order" },
      { key: "login", label: "Login" },
      { key: "symbol", label: "Symbol" },
      { key: "type", label: "Type" },
      { key: "state", label: "State" },
      { key: "volume", label: "Volume" },
      { key: "price_order", label: "Price" },
    ],
  },
  balance: {
    type: "legacy",
    title: "Balance Operations",
    legacySrc: "/modules/manager/balance.html",
  },
  groups: {
    type: "list",
    title: "Groups",
    endpoint: "/api/v1/groups",
    query: { flat: "1", limit: "500" },
    idKey: "group_id",
    pathKey: "group",
    columns: groupColumns(),
  },
  journal: {
    type: "list",
    title: "Journal",
    endpoint: "/api/v1/journal",
    query: { limit: "200" },
    idKey: "journal_id",
    search: false,
    columns: [
      tsCol("created_at", "Time"),
      { key: "channel", label: "Channel" },
      { key: "ip", label: "IP" },
      { key: "message", label: "Message" },
    ],
  },
};
