-- Orders, positions and deals, copied field for field from the MT5 SQL export
-- (sql_mt5_orders, sql_mt5_positions, sql_mt5_deals).
--
-- Two conventions carried over from the rest of this schema: times are epoch nanoseconds in
-- BIGINT rather than DateTime, and money is NUMERIC(20,8). Volume keeps the MT5 unit exactly:
-- an integer where one unit is 1/10000 lot, with the _ext column at 1/100000000 lot, the same
-- pair already used by symbols.volume_min / volume_min_ext.

CREATE TABLE IF NOT EXISTS hst.orders (
    order_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id          VARCHAR(64)      NOT NULL DEFAULT '',
    login                BIGINT           NOT NULL,
    dealer               BIGINT           NOT NULL DEFAULT 0,
    symbol               VARCHAR(32)      NOT NULL,
    digits               INTEGER          NOT NULL DEFAULT 0,
    digits_currency      INTEGER          NOT NULL DEFAULT 0,
    contract_size        NUMERIC(20,8)    NOT NULL DEFAULT 0,
    state                INTEGER          NOT NULL DEFAULT 0,
    reason               INTEGER          NOT NULL DEFAULT 0,
    time_setup           BIGINT           NOT NULL DEFAULT 0,
    time_expiration      BIGINT           NOT NULL DEFAULT 0,
    time_done            BIGINT           NOT NULL DEFAULT 0,
    modify_flags         INTEGER          NOT NULL DEFAULT 0,
    type                 INTEGER          NOT NULL DEFAULT 0,
    type_fill            INTEGER          NOT NULL DEFAULT 0,
    type_time            INTEGER          NOT NULL DEFAULT 0,
    price_order          NUMERIC(20,8)    NOT NULL DEFAULT 0,
    price_trigger        NUMERIC(20,8)    NOT NULL DEFAULT 0,
    price_current        NUMERIC(20,8)    NOT NULL DEFAULT 0,
    price_sl             NUMERIC(20,8)    NOT NULL DEFAULT 0,
    price_tp             NUMERIC(20,8)    NOT NULL DEFAULT 0,
    volume_initial       BIGINT           NOT NULL DEFAULT 0,
    volume_initial_ext   BIGINT           NOT NULL DEFAULT 0,
    volume_current       BIGINT           NOT NULL DEFAULT 0,
    volume_current_ext   BIGINT           NOT NULL DEFAULT 0,
    expert_id            BIGINT           NOT NULL DEFAULT 0,
    position_id          BIGINT           NOT NULL DEFAULT 0,
    position_by_id       BIGINT           NOT NULL DEFAULT 0,
    comment              VARCHAR(64)      NOT NULL DEFAULT '',
    activation_mode      INTEGER          NOT NULL DEFAULT 0,
    activation_time      BIGINT           NOT NULL DEFAULT 0,
    activation_price     NUMERIC(20,8)    NOT NULL DEFAULT 0,
    activation_flags     INTEGER          NOT NULL DEFAULT 0,
    rate_margin          NUMERIC(20,8)    NOT NULL DEFAULT 0,
    api_data             VARCHAR(1024)    NOT NULL DEFAULT '',
    date_created         BIGINT           NOT NULL DEFAULT 0,
    date_modified        BIGINT           NOT NULL DEFAULT 0
);

-- the engine reads a login's live orders on every tick, so the open set is the index that matters
CREATE INDEX IF NOT EXISTS orders_login_idx    ON hst.orders (login, state);
CREATE INDEX IF NOT EXISTS orders_symbol_idx   ON hst.orders (symbol, state);
CREATE INDEX IF NOT EXISTS orders_position_idx ON hst.orders (position_id);

CREATE TABLE IF NOT EXISTS hst.positions (
    position_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id          VARCHAR(64)      NOT NULL DEFAULT '',
    login                BIGINT           NOT NULL,
    dealer               BIGINT           NOT NULL DEFAULT 0,
    symbol               VARCHAR(32)      NOT NULL,
    action               INTEGER          NOT NULL DEFAULT 0,
    digits               INTEGER          NOT NULL DEFAULT 0,
    digits_currency      INTEGER          NOT NULL DEFAULT 0,
    reason               INTEGER          NOT NULL DEFAULT 0,
    contract_size        NUMERIC(20,8)    NOT NULL DEFAULT 0,
    time_create          BIGINT           NOT NULL DEFAULT 0,
    time_update          BIGINT           NOT NULL DEFAULT 0,
    price_open           NUMERIC(20,8)    NOT NULL DEFAULT 0,
    price_current        NUMERIC(20,8)    NOT NULL DEFAULT 0,
    price_sl             NUMERIC(20,8)    NOT NULL DEFAULT 0,
    price_tp             NUMERIC(20,8)    NOT NULL DEFAULT 0,
    volume               BIGINT           NOT NULL DEFAULT 0,
    volume_ext           BIGINT           NOT NULL DEFAULT 0,
    profit               NUMERIC(20,8)    NOT NULL DEFAULT 0,
    storage              NUMERIC(20,8)    NOT NULL DEFAULT 0,
    rate_profit          NUMERIC(20,8)    NOT NULL DEFAULT 0,
    rate_margin          NUMERIC(20,8)    NOT NULL DEFAULT 0,
    expert_id            BIGINT           NOT NULL DEFAULT 0,
    expert_position_id   BIGINT           NOT NULL DEFAULT 0,
    comment              VARCHAR(64)      NOT NULL DEFAULT '',
    activation_mode      INTEGER          NOT NULL DEFAULT 0,
    activation_time      BIGINT           NOT NULL DEFAULT 0,
    activation_price     NUMERIC(20,8)    NOT NULL DEFAULT 0,
    activation_flags     INTEGER          NOT NULL DEFAULT 0,
    api_data             VARCHAR(1024)    NOT NULL DEFAULT '',
    date_created         BIGINT           NOT NULL DEFAULT 0,
    date_modified        BIGINT           NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS positions_login_idx  ON hst.positions (login);
CREATE INDEX IF NOT EXISTS positions_symbol_idx ON hst.positions (symbol);
-- netting keeps at most one position per login and symbol; the engine relies on finding it fast
CREATE INDEX IF NOT EXISTS positions_netting_idx ON hst.positions (login, symbol);

CREATE TABLE IF NOT EXISTS hst.deals (
    deal_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id          VARCHAR(64)      NOT NULL DEFAULT '',
    login                BIGINT           NOT NULL,
    dealer               BIGINT           NOT NULL DEFAULT 0,
    order_id             BIGINT           NOT NULL DEFAULT 0,
    action               INTEGER          NOT NULL DEFAULT 0,
    entry                INTEGER          NOT NULL DEFAULT 0,
    digits               INTEGER          NOT NULL DEFAULT 0,
    digits_currency      INTEGER          NOT NULL DEFAULT 0,
    contract_size        NUMERIC(20,8)    NOT NULL DEFAULT 0,
    time                 BIGINT           NOT NULL DEFAULT 0,
    symbol               VARCHAR(32)      NOT NULL DEFAULT '',
    price                NUMERIC(20,8)    NOT NULL DEFAULT 0,
    price_sl             NUMERIC(20,8)    NOT NULL DEFAULT 0,
    price_tp             NUMERIC(20,8)    NOT NULL DEFAULT 0,
    volume               BIGINT           NOT NULL DEFAULT 0,
    volume_ext           BIGINT           NOT NULL DEFAULT 0,
    volume_closed        BIGINT           NOT NULL DEFAULT 0,
    volume_closed_ext    BIGINT           NOT NULL DEFAULT 0,
    profit               NUMERIC(20,8)    NOT NULL DEFAULT 0,
    value                NUMERIC(20,8)    NOT NULL DEFAULT 0,
    storage              NUMERIC(20,8)    NOT NULL DEFAULT 0,
    commission           NUMERIC(20,8)    NOT NULL DEFAULT 0,
    fee                  NUMERIC(20,8)    NOT NULL DEFAULT 0,
    rate_profit          NUMERIC(20,8)    NOT NULL DEFAULT 0,
    rate_margin          NUMERIC(20,8)    NOT NULL DEFAULT 0,
    expert_id            BIGINT           NOT NULL DEFAULT 0,
    position_id          BIGINT           NOT NULL DEFAULT 0,
    comment              VARCHAR(64)      NOT NULL DEFAULT '',
    profit_raw           NUMERIC(20,8)    NOT NULL DEFAULT 0,
    price_position       NUMERIC(20,8)    NOT NULL DEFAULT 0,
    tick_value           NUMERIC(20,8)    NOT NULL DEFAULT 0,
    tick_size            NUMERIC(20,8)    NOT NULL DEFAULT 0,
    flags                INTEGER          NOT NULL DEFAULT 0,
    reason               INTEGER          NOT NULL DEFAULT 0,
    gateway              VARCHAR(32)      NOT NULL DEFAULT '',
    price_gateway        NUMERIC(20,8)    NOT NULL DEFAULT 0,
    market_bid           NUMERIC(20,8)    NOT NULL DEFAULT 0,
    market_ask           NUMERIC(20,8)    NOT NULL DEFAULT 0,
    market_last          NUMERIC(20,8)    NOT NULL DEFAULT 0,
    api_data             VARCHAR(1024)    NOT NULL DEFAULT '',
    date_created         BIGINT           NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS deals_login_time_idx ON hst.deals (login, time DESC);
CREATE INDEX IF NOT EXISTS deals_position_idx   ON hst.deals (position_id);
CREATE INDEX IF NOT EXISTS deals_order_idx      ON hst.deals (order_id);

-- What the engine closed and why. A stop out that cannot be explained afterwards is not defensible.
CREATE TABLE IF NOT EXISTS hst.stopout_log (
    stopout_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login                BIGINT           NOT NULL,
    position_id          BIGINT           NOT NULL DEFAULT 0,
    symbol               VARCHAR(32)      NOT NULL DEFAULT '',
    time                 BIGINT           NOT NULL DEFAULT 0,
    equity               NUMERIC(20,8)    NOT NULL DEFAULT 0,
    margin               NUMERIC(20,8)    NOT NULL DEFAULT 0,
    margin_level         NUMERIC(20,8)    NOT NULL DEFAULT 0,
    so_level             NUMERIC(20,8)    NOT NULL DEFAULT 0,
    volume_closed        BIGINT           NOT NULL DEFAULT 0,
    profit               NUMERIC(20,8)    NOT NULL DEFAULT 0,
    comment              VARCHAR(128)     NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS stopout_login_idx ON hst.stopout_log (login, time DESC);

-- The Dealers tab of a routing rule (mt5_routing_dealers). Only a manager holding the dealing
-- right, or a gateway, belongs here.
CREATE TABLE IF NOT EXISTS hst.routing_dealers (
    dealer_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    routing_id           BIGINT           NOT NULL REFERENCES hst.routing(routing_id) ON DELETE CASCADE,
    login                BIGINT           NOT NULL,
    name                 VARCHAR(128)     NOT NULL DEFAULT ''
);

CREATE UNIQUE INDEX IF NOT EXISTS routing_dealers_uidx ON hst.routing_dealers (routing_id, login);
