-- Market Watch favourites: a login's named lists and the symbols inside them.

CREATE TABLE IF NOT EXISTS hst.watchlists (
    watchlist_id BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login        BIGINT       NOT NULL,
    name         VARCHAR(128) NOT NULL,
    kind         INTEGER      NOT NULL DEFAULT 0,
    sort_order   INTEGER      NOT NULL DEFAULT 0,
    created_at   BIGINT       NOT NULL DEFAULT 0,
    updated_at   BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT watchlists_name_set CHECK (name <> '')
);

CREATE INDEX IF NOT EXISTS watchlists_login_idx ON hst.watchlists (login);

CREATE TABLE IF NOT EXISTS hst.watchlist_symbols (
    watchlist_id BIGINT  NOT NULL
                 REFERENCES hst.watchlists (watchlist_id) ON DELETE CASCADE,
    symbol_id    BIGINT  NOT NULL REFERENCES hst.symbols (symbol_id) ON DELETE CASCADE,
    sort_order   INTEGER NOT NULL DEFAULT 0,

    PRIMARY KEY (watchlist_id, symbol_id)
);

COMMENT ON TABLE hst.watchlists IS
    'per login Market Watch lists';
COMMENT ON COLUMN hst.watchlists.kind IS
    'caller defined list kind, 0 is the plain favourites list';
COMMENT ON COLUMN hst.watchlists.created_at IS
    'unix nanoseconds';
