CREATE TABLE IF NOT EXISTS hst.datafeeds (
    datafeed_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(64)  NOT NULL,
    module              VARCHAR(128) NOT NULL,
    enable              SMALLINT     NOT NULL DEFAULT 1,
    mode                INTEGER      NOT NULL DEFAULT 1,
    gateway_server      VARCHAR(255) NOT NULL DEFAULT '',
    feed_server         VARCHAR(255) NOT NULL DEFAULT '',
    feed_login          BIGINT       NOT NULL DEFAULT 0,
    feed_password       TEXT         NOT NULL DEFAULT '',
    gateway_login       BIGINT       NOT NULL DEFAULT 0,
    gateway_password    TEXT         NOT NULL DEFAULT '',
    timeout             INTEGER      NOT NULL DEFAULT 0,
    timeout_reconnect   INTEGER      NOT NULL DEFAULT 5,
    timeout_sleep       INTEGER      NOT NULL DEFAULT 60,
    attempts_sleep      INTEGER      NOT NULL DEFAULT 10,
    updated_at          BIGINT       NOT NULL DEFAULT 0,
    company             VARCHAR(255) NOT NULL DEFAULT '',
    issuer              VARCHAR(255) NOT NULL DEFAULT '',
    sys_connection      SMALLINT     NOT NULL DEFAULT 0,
    sys_last_time       BIGINT       NOT NULL DEFAULT 0,
    tick_stats_count    BIGINT       NOT NULL DEFAULT 0,
    ticks_count         BIGINT       NOT NULL DEFAULT 0,
    books_count         BIGINT       NOT NULL DEFAULT 0,
    news_count          BIGINT       NOT NULL DEFAULT 0,
    bytes_received      BIGINT       NOT NULL DEFAULT 0,
    bytes_sent          BIGINT       NOT NULL DEFAULT 0,
    state_flags         INTEGER      NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS datafeeds_name_uidx ON hst.datafeeds (name);
CREATE INDEX IF NOT EXISTS datafeeds_enable_idx ON hst.datafeeds (enable);

CREATE TABLE IF NOT EXISTS hst.datafeed_params (
    param_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    datafeed_id BIGINT       NOT NULL REFERENCES hst.datafeeds (datafeed_id) ON DELETE CASCADE,
    param_key   VARCHAR(64)  NOT NULL,
    type        SMALLINT     NOT NULL DEFAULT 0,
    value       TEXT         NOT NULL DEFAULT '',
    priority    INTEGER      NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS datafeed_params_feed_key_uidx
    ON hst.datafeed_params (datafeed_id, param_key);

CREATE UNIQUE INDEX IF NOT EXISTS datafeed_params_feed_priority_uidx
    ON hst.datafeed_params (datafeed_id, priority);

CREATE TABLE IF NOT EXISTS hst.datafeed_translates (
    translate_id BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    datafeed_id  BIGINT       NOT NULL REFERENCES hst.datafeeds (datafeed_id) ON DELETE CASCADE,
    symbol_id    BIGINT       NOT NULL REFERENCES hst.symbols (symbol_id) ON DELETE CASCADE,
    symbol       VARCHAR(255) NOT NULL,
    source       VARCHAR(255) NOT NULL DEFAULT '',
    bid_markup   INTEGER      NOT NULL DEFAULT 0,
    ask_markup   INTEGER      NOT NULL DEFAULT 0,
    digits       SMALLINT     NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS datafeed_translates_feed_symbol_id_uidx
    ON hst.datafeed_translates (datafeed_id, symbol_id);

CREATE TABLE IF NOT EXISTS hst.datafeed_symbols (
    feed_symbol_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    datafeed_id    BIGINT       NOT NULL REFERENCES hst.datafeeds (datafeed_id) ON DELETE CASCADE,
    symbol_id      BIGINT       REFERENCES hst.symbols (symbol_id) ON DELETE CASCADE,
    path           VARCHAR(255) NOT NULL DEFAULT '',
    exclude        SMALLINT     NOT NULL DEFAULT 0,
    symbol         VARCHAR(255) NOT NULL DEFAULT '',
    CONSTRAINT datafeed_symbols_exclude_chk CHECK (exclude IN (0, 1)),
    CONSTRAINT datafeed_symbols_target_chk CHECK (symbol_id IS NOT NULL OR path <> '')
);

CREATE INDEX IF NOT EXISTS datafeed_symbols_feed_idx
    ON hst.datafeed_symbols (datafeed_id, feed_symbol_id);

CREATE UNIQUE INDEX IF NOT EXISTS datafeed_symbols_feed_symbol_uidx
    ON hst.datafeed_symbols (datafeed_id, symbol_id)
    WHERE symbol_id IS NOT NULL;

COMMENT ON TABLE hst.datafeeds IS 'MT5 data feed configuration; runtime counters updated by quote service only';
COMMENT ON COLUMN hst.datafeeds.enable IS '0=disabled 1=enabled';
COMMENT ON COLUMN hst.datafeeds.mode IS 'EnFeederFlags bitmask: 1=quotes 2=news 8=remote';
COMMENT ON COLUMN hst.datafeeds.feed_password IS 'write-only; omitted from API responses';
COMMENT ON COLUMN hst.datafeeds.gateway_password IS 'write-only; omitted from API responses';
COMMENT ON COLUMN hst.datafeeds.sys_connection IS '0=no connection 1=connected; quote service only';
COMMENT ON COLUMN hst.datafeeds.updated_at IS 'unix nanoseconds';

COMMENT ON COLUMN hst.datafeed_params.type IS 'FeederParamType: 0=string 1=int 2=float 3=time 4=date 5=datetime 6=groups 7=symbols 8=bool 9=color';
COMMENT ON COLUMN hst.datafeed_params.priority IS
    'Order within one feed only (0-based). Unique together with datafeed_id, not globally.';

COMMENT ON TABLE hst.datafeed_translates IS 'symbol name and price translation from external source to platform';
COMMENT ON COLUMN hst.datafeed_translates.symbol IS 'denormalized platform symbol name from catalog';
COMMENT ON COLUMN hst.datafeed_translates.symbol_id IS 'stable platform symbol reference';

COMMENT ON TABLE hst.datafeed_symbols IS
    'MT5 Symbols tab rows: explicit symbol_id or path mask with optional exclude';
COMMENT ON COLUMN hst.datafeed_symbols.path IS
    'path/name mask when symbol_id is null (e.g. *, Forex\\*, EURUSD)';
COMMENT ON COLUMN hst.datafeed_symbols.exclude IS
    '0=include matched symbols, 1=exclude matched symbols (applied in row order)';
