CREATE SCHEMA IF NOT EXISTS hst;

CREATE TABLE IF NOT EXISTS hst.clients (
    client_id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_type                 SMALLINT      NOT NULL DEFAULT 0,
    client_status               SMALLINT      NOT NULL DEFAULT 0,
    kyc_status                  SMALLINT      NOT NULL DEFAULT 0,
    assigned_manager            BIGINT,
    compliance_approved_by      BIGINT,
    compliance_client_category  VARCHAR(64)   NOT NULL DEFAULT '',
    compliance_date_approval    BIGINT NOT NULL DEFAULT 0,
    compliance_date_termination BIGINT NOT NULL DEFAULT 0,
    comment                     TEXT          NOT NULL DEFAULT '',

    lead_campaign               VARCHAR(128)  NOT NULL DEFAULT '',
    lead_source                 VARCHAR(255)  NOT NULL DEFAULT '',
    introducer                  BIGINT,
    client_origin               SMALLINT      NOT NULL DEFAULT 0,
    client_origin_login         BIGINT,

    person_title                VARCHAR(32)   NOT NULL DEFAULT '',
    person_name                 VARCHAR(128)  NOT NULL DEFAULT '',
    person_middle_name          VARCHAR(64)   NOT NULL DEFAULT '',
    person_birth_date           BIGINT NOT NULL DEFAULT 0,
    person_citizenship          VARCHAR(64)   NOT NULL DEFAULT '',
    person_gender               SMALLINT      NOT NULL DEFAULT 0,
    person_tax_id               VARCHAR(64)   NOT NULL DEFAULT '',
    person_document_type        VARCHAR(64)   NOT NULL DEFAULT '',
    person_document_number      VARCHAR(64)   NOT NULL DEFAULT '',
    person_document_date        BIGINT NOT NULL DEFAULT 0,
    person_document_extra       TEXT          NOT NULL DEFAULT '',
    person_employment           SMALLINT      NOT NULL DEFAULT 0,
    person_industry             SMALLINT      NOT NULL DEFAULT 0,
    person_education            SMALLINT      NOT NULL DEFAULT 0,
    person_wealth_source        SMALLINT      NOT NULL DEFAULT 0,
    person_annual_income        NUMERIC(20,8) NOT NULL DEFAULT 0,
    person_net_worth            NUMERIC(20,8) NOT NULL DEFAULT 0,
    person_annual_deposit       NUMERIC(20,8) NOT NULL DEFAULT 0,

    company_name                VARCHAR(255)  NOT NULL DEFAULT '',
    company_reg_number          VARCHAR(64)   NOT NULL DEFAULT '',
    company_reg_date            VARCHAR(32)   NOT NULL DEFAULT '',
    company_reg_authority       VARCHAR(255)  NOT NULL DEFAULT '',
    company_vat                 VARCHAR(64)   NOT NULL DEFAULT '',
    company_lei                 VARCHAR(20)   NOT NULL DEFAULT '',
    company_license_number      VARCHAR(64)   NOT NULL DEFAULT '',
    company_license_authority   VARCHAR(255)  NOT NULL DEFAULT '',
    company_country             VARCHAR(64)   NOT NULL DEFAULT '',
    company_address             TEXT          NOT NULL DEFAULT '',
    company_website             VARCHAR(255)  NOT NULL DEFAULT '',

    contact_preferred           SMALLINT      NOT NULL DEFAULT 0,
    contact_language            VARCHAR(16)   NOT NULL DEFAULT '',
    contact_email               VARCHAR(255)  NOT NULL DEFAULT '',
    contact_phone               VARCHAR(64)   NOT NULL DEFAULT '',
    contact_messengers          TEXT          NOT NULL DEFAULT '',
    contact_social_networks     TEXT          NOT NULL DEFAULT '',
    contact_last_date           BIGINT NOT NULL DEFAULT 0,

    address_country             VARCHAR(64)   NOT NULL DEFAULT '',
    address_postcode            VARCHAR(32)   NOT NULL DEFAULT '',
    address_street              TEXT          NOT NULL DEFAULT '',
    address_state               VARCHAR(64)   NOT NULL DEFAULT '',
    address_city                VARCHAR(64)   NOT NULL DEFAULT '',

    experience_fx               SMALLINT      NOT NULL DEFAULT 0,
    experience_cfd              SMALLINT      NOT NULL DEFAULT 0,
    experience_futures          SMALLINT      NOT NULL DEFAULT 0,
    experience_stocks           SMALLINT      NOT NULL DEFAULT 0,

    date_created                BIGINT   NOT NULL DEFAULT 0,
    date_modified               BIGINT   NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS clients_assigned_manager_idx ON hst.clients (assigned_manager);
CREATE INDEX IF NOT EXISTS clients_contact_email_idx    ON hst.clients (contact_email);
CREATE INDEX IF NOT EXISTS clients_introducer_idx       ON hst.clients (introducer);

COMMENT ON COLUMN hst.clients.client_type IS
    'EnClientType: 0=undefined 1=individual 2=corporate 3=fund';
COMMENT ON COLUMN hst.clients.client_status IS
    'EnClientStatus: 0=unregistered 100=registered 200=not_interested 300=application_incompleted 400=application_completed 500=application_information 600=application_rejected 700=approved';
COMMENT ON COLUMN hst.clients.kyc_status IS
    'EnKYCStatus: 0=undefined 1=approved 2=declined';
COMMENT ON COLUMN hst.clients.person_gender IS
    'EnGender: 0=unspecified 1=male 2=female';
COMMENT ON COLUMN hst.clients.person_employment IS
    'EnEmployment: 0=unemployed 1=employed 2=self_employed 3=retired 4=student 5=other';
COMMENT ON COLUMN hst.clients.person_industry IS
    'EnEmploymentIndustry: 0=undefined, 1..16 industry codes';
COMMENT ON COLUMN hst.clients.person_education IS
    'EnEducationLevel: 0=none 1=high_school 2=bachelor 3=master 4=phd 5=other';
COMMENT ON COLUMN hst.clients.person_wealth_source IS
    'EnWealthSource: 0=employment 1=savings 2=inheritance 3=other';
COMMENT ON COLUMN hst.clients.contact_preferred IS
    'EnPreferredCommunication: 0=undefined 1=email 2=phone 3=phone_sms 4=messenger';
COMMENT ON COLUMN hst.clients.client_origin IS
    'EnClientOrigin: 0=manual 1=demo 2=contest 3=preliminary 4=real';
COMMENT ON COLUMN hst.clients.experience_fx IS
    'EnTradingExperience: 0=less_1_year 1=1_3_year 2=above_3_year';
COMMENT ON COLUMN hst.clients.experience_cfd IS
    'EnTradingExperience: 0=less_1_year 1=1_3_year 2=above_3_year';
COMMENT ON COLUMN hst.clients.experience_futures IS
    'EnTradingExperience: 0=less_1_year 1=1_3_year 2=above_3_year';
COMMENT ON COLUMN hst.clients.experience_stocks IS
    'EnTradingExperience: 0=less_1_year 1=1_3_year 2=above_3_year';

COMMENT ON TABLE hst.clients IS 'all time columns are unix nanoseconds, 0 means unset';
