CREATE TABLE IF NOT EXISTS hst.symbols (
    symbol_id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol                       VARCHAR(64)      NOT NULL,
    path                         VARCHAR(255)     NOT NULL,
    isin                         VARCHAR(32)      NOT NULL DEFAULT '',
    description                  VARCHAR(255)     NOT NULL DEFAULT '',
    international                VARCHAR(64)      NOT NULL DEFAULT '',
    category                     VARCHAR(128)     NOT NULL DEFAULT '',
    exchange                     VARCHAR(128)     NOT NULL DEFAULT '',
    cfi                          VARCHAR(16)      NOT NULL DEFAULT '',
    sector                       SMALLINT         NOT NULL DEFAULT 0,
    industry                     INTEGER          NOT NULL DEFAULT 0,
    country                      VARCHAR(64)      NOT NULL DEFAULT '',
    basis                        VARCHAR(64)      NOT NULL DEFAULT '',
    source                       VARCHAR(128)     NOT NULL DEFAULT '',
    page                         VARCHAR(255)     NOT NULL DEFAULT '',
    currency_base                VARCHAR(16)      NOT NULL DEFAULT '',
    currency_base_digits         SMALLINT         NOT NULL DEFAULT 0,
    currency_profit              VARCHAR(16)      NOT NULL DEFAULT '',
    currency_profit_digits       SMALLINT         NOT NULL DEFAULT 0,
    currency_margin              VARCHAR(16)      NOT NULL DEFAULT '',
    currency_margin_digits       SMALLINT         NOT NULL DEFAULT 0,
    color                        BIGINT           NOT NULL DEFAULT 0,
    color_background             BIGINT           NOT NULL DEFAULT 0,
    digits                       SMALLINT         NOT NULL DEFAULT 5,
    point                        NUMERIC(20,8)    NOT NULL DEFAULT 0.00001,
    multiply                     NUMERIC(20,8)    NOT NULL DEFAULT 100000,
    tick_flags                   INTEGER          NOT NULL DEFAULT 0,
    tick_book_depth              INTEGER          NOT NULL DEFAULT 0,
    filter_soft                  INTEGER          NOT NULL DEFAULT 0,
    filter_soft_ticks            INTEGER          NOT NULL DEFAULT 0,
    filter_hard                  INTEGER          NOT NULL DEFAULT 0,
    filter_hard_ticks            INTEGER          NOT NULL DEFAULT 0,
    filter_discard               INTEGER          NOT NULL DEFAULT 0,
    filter_spread_max            INTEGER          NOT NULL DEFAULT 0,
    filter_spread_min            INTEGER          NOT NULL DEFAULT 0,
    subscriptions_delay          INTEGER          NOT NULL DEFAULT 0,
    trade_mode                   SMALLINT         NOT NULL DEFAULT 4,
    calc_mode                    SMALLINT         NOT NULL DEFAULT 0,
    exec_mode                    SMALLINT         NOT NULL DEFAULT 2,
    gtc_mode                     SMALLINT         NOT NULL DEFAULT 0,
    fill_flags                   INTEGER          NOT NULL DEFAULT 0,
    expir_flags                  INTEGER          NOT NULL DEFAULT 0,
    spread                       INTEGER          NOT NULL DEFAULT 0,
    spread_balance               INTEGER          NOT NULL DEFAULT 0,
    spread_diff                  INTEGER          NOT NULL DEFAULT 0,
    spread_diff_balance          INTEGER          NOT NULL DEFAULT 0,
    tick_value                   NUMERIC(20,8)    NOT NULL DEFAULT 0,
    tick_size                    NUMERIC(20,8)    NOT NULL DEFAULT 0,
    contract_size                NUMERIC(20,8)    NOT NULL DEFAULT 100000,
    stops_level                  INTEGER          NOT NULL DEFAULT 0,
    freeze_level                 INTEGER          NOT NULL DEFAULT 0,
    quotes_timeout               INTEGER          NOT NULL DEFAULT 0,
    volume_min                   BIGINT           NOT NULL DEFAULT 10000,
    volume_min_ext               BIGINT           NOT NULL DEFAULT 0,
    volume_max                   BIGINT           NOT NULL DEFAULT 100000000,
    volume_max_ext               BIGINT           NOT NULL DEFAULT 0,
    volume_step                  BIGINT           NOT NULL DEFAULT 10000,
    volume_step_ext              BIGINT           NOT NULL DEFAULT 0,
    volume_limit                 BIGINT           NOT NULL DEFAULT 0,
    volume_limit_ext             BIGINT           NOT NULL DEFAULT 0,
    margin_flags                 INTEGER          NOT NULL DEFAULT 0,
    margin_initial               NUMERIC(20,8)    NOT NULL DEFAULT 0,
    margin_maintenance           NUMERIC(20,8)    NOT NULL DEFAULT 0,
    margin_initial_buy           NUMERIC(20,8)    NOT NULL DEFAULT 0,
    margin_initial_sell          NUMERIC(20,8)    NOT NULL DEFAULT 0,
    margin_initial_buy_limit     NUMERIC(20,8)    NOT NULL DEFAULT 0,
    margin_initial_sell_limit    NUMERIC(20,8)    NOT NULL DEFAULT 0,
    margin_initial_buy_stop      NUMERIC(20,8)    NOT NULL DEFAULT 0,
    margin_initial_sell_stop     NUMERIC(20,8)    NOT NULL DEFAULT 0,
    margin_initial_buy_stop_limit NUMERIC(20,8)    NOT NULL DEFAULT 0,
    margin_initial_sell_stop_limit NUMERIC(20,8)    NOT NULL DEFAULT 0,
    margin_maintenance_buy       NUMERIC(20,8)    NOT NULL DEFAULT 0,
    margin_maintenance_sell      NUMERIC(20,8)    NOT NULL DEFAULT 0,
    margin_maintenance_buy_limit NUMERIC(20,8)    NOT NULL DEFAULT 0,
    margin_maintenance_sell_limit NUMERIC(20,8)    NOT NULL DEFAULT 0,
    margin_maintenance_buy_stop  NUMERIC(20,8)    NOT NULL DEFAULT 0,
    margin_maintenance_sell_stop NUMERIC(20,8)    NOT NULL DEFAULT 0,
    margin_maintenance_buy_stop_limit NUMERIC(20,8)    NOT NULL DEFAULT 0,
    margin_maintenance_sell_stop_limit NUMERIC(20,8)    NOT NULL DEFAULT 0,
    margin_hedged                NUMERIC(20,8)    NOT NULL DEFAULT 0,
    swap_mode                    SMALLINT         NOT NULL DEFAULT 0,
    swap_long                    NUMERIC(20,8)    NOT NULL DEFAULT 0,
    swap_short                   NUMERIC(20,8)    NOT NULL DEFAULT 0,
    swap_year_day                SMALLINT         NOT NULL DEFAULT 0,
    swap_flags                   INTEGER          NOT NULL DEFAULT 0,
    swap_rate_sunday             NUMERIC(20,8)    NOT NULL DEFAULT 1,
    swap_rate_monday             NUMERIC(20,8)    NOT NULL DEFAULT 1,
    swap_rate_tuesday            NUMERIC(20,8)    NOT NULL DEFAULT 1,
    swap_rate_wednesday          NUMERIC(20,8)    NOT NULL DEFAULT 1,
    swap_rate_thursday           NUMERIC(20,8)    NOT NULL DEFAULT 1,
    swap_rate_friday             NUMERIC(20,8)    NOT NULL DEFAULT 1,
    swap_rate_saturday           NUMERIC(20,8)    NOT NULL DEFAULT 1,
    time_start                   BIGINT           NOT NULL DEFAULT 0,
    time_expiration              BIGINT           NOT NULL DEFAULT 0,
    re_flags                     INTEGER          NOT NULL DEFAULT 0,
    re_timeout                   INTEGER          NOT NULL DEFAULT 0,
    ie_check_mode                SMALLINT         NOT NULL DEFAULT 0,
    ie_timeout                   INTEGER          NOT NULL DEFAULT 0,
    ie_slip_profit               INTEGER          NOT NULL DEFAULT 0,
    ie_slip_losing               INTEGER          NOT NULL DEFAULT 0,
    ie_volume_max                BIGINT           NOT NULL DEFAULT 0,
    ie_volume_max_ext            BIGINT           NOT NULL DEFAULT 0,
    price_settle                 NUMERIC(20,8)    NOT NULL DEFAULT 0,
    price_limit_max              NUMERIC(20,8)    NOT NULL DEFAULT 0,
    price_limit_min              NUMERIC(20,8)    NOT NULL DEFAULT 0,
    trade_flags                  INTEGER          NOT NULL DEFAULT 0,
    order_flags                  INTEGER          NOT NULL DEFAULT 0,
    margin_rate_liquidity        NUMERIC(20,8)    NOT NULL DEFAULT 0,
    margin_rate_currency         NUMERIC(20,8)    NOT NULL DEFAULT 0,
    face_value                   NUMERIC(20,8)    NOT NULL DEFAULT 0,
    accrued_interest             NUMERIC(20,8)    NOT NULL DEFAULT 0,
    splice_type                  SMALLINT         NOT NULL DEFAULT 0,
    splice_time_type             SMALLINT         NOT NULL DEFAULT 0,
    splice_time_days             INTEGER          NOT NULL DEFAULT 0,
    option_mode                  SMALLINT         NOT NULL DEFAULT 0,
    price_strike                 NUMERIC(20,8)    NOT NULL DEFAULT 0,
    filter_gap                   INTEGER          NOT NULL DEFAULT 0,
    filter_gap_ticks             INTEGER          NOT NULL DEFAULT 0,
    tick_chart_mode              SMALLINT         NOT NULL DEFAULT 0,
    date_created                BIGINT   NOT NULL DEFAULT 0,
    date_modified               BIGINT   NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS symbols_symbol_uidx ON hst.symbols (symbol);
CREATE UNIQUE INDEX IF NOT EXISTS symbols_path_uidx ON hst.symbols (path);
CREATE INDEX IF NOT EXISTS symbols_source_idx ON hst.symbols (source);

COMMENT ON COLUMN hst.symbols.sector IS
    'SymbolSector';
COMMENT ON COLUMN hst.symbols.industry IS
    'SymbolIndustry';
COMMENT ON COLUMN hst.symbols.tick_flags IS
    'TickFlags bitmask';
COMMENT ON COLUMN hst.symbols.trade_mode IS
    'TradeMode: 0=disabled 1=longonly 2=shortonly 3=closeonly 4=full';
COMMENT ON COLUMN hst.symbols.calc_mode IS
    'CalcMode: 0=forex 1=futures 2=cfd 3=cfdindex 4=cfdleverage 5=forex_no_leverage 32+=exchange 64=collateral';
COMMENT ON COLUMN hst.symbols.exec_mode IS
    'ExecMode: 0=request 1=instant 2=market 3=exchange';
COMMENT ON COLUMN hst.symbols.gtc_mode IS
    'GTCMode: 0=gtc 1=daily 2=daily_no_stops';
COMMENT ON COLUMN hst.symbols.fill_flags IS
    'FillingFlags bitmask';
COMMENT ON COLUMN hst.symbols.expir_flags IS
    'ExpirationFlags bitmask';
COMMENT ON COLUMN hst.symbols.spread IS
    'manual fixed spread in points; 0 = floating';
COMMENT ON COLUMN hst.symbols.spread_diff IS
    'base always 0; use groups_symbols for per-group';
COMMENT ON COLUMN hst.symbols.spread_diff_balance IS
    'base always 0; use groups_symbols for per-group';
COMMENT ON COLUMN hst.symbols.volume_min IS
    '1 unit = 1/10000 lot';
COMMENT ON COLUMN hst.symbols.volume_min_ext IS
    '1 unit = 1/100000000 lot';
COMMENT ON COLUMN hst.symbols.margin_flags IS
    'SymbolMarginFlags bitmask';
COMMENT ON COLUMN hst.symbols.swap_mode IS
    'SwapMode';
COMMENT ON COLUMN hst.symbols.swap_year_day IS
    'SwapDays triple-swap day; also days/year for percent swaps';
COMMENT ON COLUMN hst.symbols.swap_flags IS
    'SwapFlags bitmask';
COMMENT ON COLUMN hst.symbols.time_start IS
    'unix seconds; 0 with time_expiration 0 = no limit';
COMMENT ON COLUMN hst.symbols.re_flags IS
    'RequestFlags bitmask';
COMMENT ON COLUMN hst.symbols.ie_check_mode IS
    'InstantMode';
COMMENT ON COLUMN hst.symbols.trade_flags IS
    'SymbolTradeFlags bitmask';
COMMENT ON COLUMN hst.symbols.order_flags IS
    'OrderFlags bitmask';
COMMENT ON COLUMN hst.symbols.splice_type IS
    'SpliceType';
COMMENT ON COLUMN hst.symbols.splice_time_type IS
    'SpliceTimeType';
COMMENT ON COLUMN hst.symbols.option_mode IS
    'OptionMode';
COMMENT ON COLUMN hst.symbols.tick_chart_mode IS
    'ChartMode: 0=bid 1=last';

COMMENT ON TABLE hst.symbols IS 'all time columns are unix nanoseconds except time_start/time_expiration (unix seconds, MT5); 0 means unset';

CREATE TABLE IF NOT EXISTS hst.symbols_sessions (
    session_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol_id   BIGINT NOT NULL REFERENCES hst.symbols(symbol_id) ON DELETE CASCADE,
    type        SMALLINT NOT NULL,
    day         SMALLINT NOT NULL,
    open        INTEGER  NOT NULL,
    close       INTEGER  NOT NULL,
    CONSTRAINT symbols_sessions_type_chk CHECK (type IN (0, 1)),
    CONSTRAINT symbols_sessions_day_chk CHECK (day BETWEEN 0 AND 6),
    CONSTRAINT symbols_sessions_open_chk CHECK (open >= 0),
    CONSTRAINT symbols_sessions_close_chk CHECK (close <= 1440),
    CONSTRAINT symbols_sessions_range_chk CHECK (open < close)
);

CREATE INDEX IF NOT EXISTS symbols_sessions_symbol_type_day_idx
    ON hst.symbols_sessions (symbol_id, type, day);

COMMENT ON COLUMN hst.symbols_sessions.type IS
    '0=quote 1=trade';
COMMENT ON COLUMN hst.symbols_sessions.day IS
    '0=Sunday .. 6=Saturday';
COMMENT ON COLUMN hst.symbols_sessions.open IS
    'minutes since 00:00';
COMMENT ON COLUMN hst.symbols_sessions.close IS
    'minutes since 00:00; max 1440';
COMMENT ON TABLE hst.symbols_sessions IS 'quote/trade session windows per symbol per weekday';
