-- Holiday calendar: one row narrows the server work time for a set of symbol
-- masks on one date. Column names follow the export, lowercased; from,
-- to and timestamp are quoted because they are SQL reserved words.

CREATE TABLE IF NOT EXISTS hst.holidays (
    holiday_id   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year         INTEGER      NOT NULL DEFAULT 0,
    month        SMALLINT     NOT NULL,
    day          SMALLINT     NOT NULL,
    "from"       INTEGER      NOT NULL DEFAULT 0,
    "to"         INTEGER      NOT NULL DEFAULT 0,
    description  VARCHAR(128) NOT NULL DEFAULT '',
    "timestamp"  BIGINT       NOT NULL DEFAULT 0,
    mode         SMALLINT     NOT NULL DEFAULT 1,
    symbols      TEXT[]       NOT NULL DEFAULT '{}',
    config_index INTEGER      NOT NULL,

    CONSTRAINT holidays_year_chk    CHECK (year = 0 OR year BETWEEN 1970 AND 9999),
    CONSTRAINT holidays_month_chk   CHECK (month BETWEEN 1 AND 12),
    CONSTRAINT holidays_day_chk     CHECK (day BETWEEN 1 AND 31),
    CONSTRAINT holidays_from_chk    CHECK ("from" BETWEEN 0 AND 1439),
    CONSTRAINT holidays_to_chk      CHECK ("to" BETWEEN 0 AND 1439),
    CONSTRAINT holidays_range_chk   CHECK ("to" >= "from"),
    CONSTRAINT holidays_mode_chk    CHECK (mode IN (0, 1)),
    CONSTRAINT holidays_symbols_set CHECK (cardinality(symbols) > 0),
    CONSTRAINT holidays_order       UNIQUE (config_index)
);

CREATE INDEX IF NOT EXISTS holidays_date_idx ON hst.holidays (month, day);

COMMENT ON TABLE hst.holidays IS
    'trading holiday calendar, applied to symbols by mask';
COMMENT ON COLUMN hst.holidays.year IS
    '0 means the holiday repeats every year';
COMMENT ON COLUMN hst.holidays.month IS
    '1=January .. 12=December';
COMMENT ON COLUMN hst.holidays.day IS
    '1..31, checked against the real calendar in Go';
COMMENT ON COLUMN hst.holidays."from" IS
    'server work time start, minutes since 00:00; 0 with "to" 0 means closed all day';
COMMENT ON COLUMN hst.holidays."to" IS
    'server work time end, minutes since 00:00, inclusive: 1080 stays open through 18:00:59';
COMMENT ON COLUMN hst.holidays."timestamp" IS
    'change marker, unix nanoseconds; a changed value means a changed record';
COMMENT ON COLUMN hst.holidays.mode IS
    '0=disabled 1=enabled';
COMMENT ON COLUMN hst.holidays.symbols IS
    'symbol or group masks, for example {EURUSD,"CFD\*"}; * matches every symbol';
COMMENT ON COLUMN hst.holidays.config_index IS
    'list order, 0 based; kept for parity and export, the resolver is order independent';
