CREATE TABLE IF NOT EXISTS hst.routing (
    routing_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 VARCHAR(128)     NOT NULL,
    mode                 SMALLINT         NOT NULL DEFAULT 1,
    request              INTEGER          NOT NULL DEFAULT 0,
    type                 INTEGER          NOT NULL DEFAULT 0,
    flags                INTEGER          NOT NULL DEFAULT 0,
    action               INTEGER          NOT NULL,
    action_value         VARCHAR(1024)    NOT NULL DEFAULT '',
    routing_index        INTEGER          NOT NULL,
    date_created         BIGINT           NOT NULL DEFAULT 0,
    date_modified        BIGINT           NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS routing_name_uidx  ON hst.routing (name);
CREATE UNIQUE INDEX IF NOT EXISTS routing_index_uidx ON hst.routing (routing_index);

CREATE TABLE IF NOT EXISTS hst.routing_conds (
    condition_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    routing_id     BIGINT NOT NULL REFERENCES hst.routing(routing_id) ON DELETE CASCADE,
    condition      INTEGER          NOT NULL,
    rule           SMALLINT         NOT NULL,
    value          VARCHAR(1024)    NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS routing_conds_routing_idx
    ON hst.routing_conds (routing_id, condition_id);
