-- Floating leverage configuration: profiles hold ordered rules, rules hold
-- ordered tiers. Column names follow the MT5 SQL export, lowercased.

CREATE TABLE IF NOT EXISTS hst.leverages (
    leverage_id  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(128) NOT NULL,
    "timestamp"  BIGINT       NOT NULL DEFAULT 0,
    flags        INTEGER      NOT NULL DEFAULT 0,

    CONSTRAINT leverages_name_set    CHECK (name <> ''),
    CONSTRAINT leverages_name_unique UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS hst.leverage_rules (
    rule_id                     BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leverage_id                 BIGINT       NOT NULL
                                REFERENCES hst.leverages (leverage_id) ON DELETE CASCADE,
    name                        VARCHAR(128) NOT NULL,
    description                 VARCHAR(255) NOT NULL DEFAULT '',
    path                        VARCHAR(128) NOT NULL,
    range_mode                  SMALLINT     NOT NULL DEFAULT 0,
    range_value_currency        VARCHAR(8)   NOT NULL DEFAULT '',
    range_value_currency_digits SMALLINT     NOT NULL DEFAULT 2,
    config_index                INTEGER      NOT NULL DEFAULT 0,

    CONSTRAINT leverage_rules_name_set   CHECK (name <> ''),
    CONSTRAINT leverage_rules_path_set   CHECK (path <> ''),
    CONSTRAINT leverage_rules_range_mode CHECK (range_mode BETWEEN 0 AND 3),
    CONSTRAINT leverage_rules_order      UNIQUE (leverage_id, config_index)
);

CREATE INDEX IF NOT EXISTS leverage_rules_leverage_id_idx
    ON hst.leverage_rules (leverage_id);

CREATE TABLE IF NOT EXISTS hst.leverage_tiers (
    tier_id                 BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id                 BIGINT        NOT NULL
                            REFERENCES hst.leverage_rules (rule_id) ON DELETE CASCADE,
    range_from              NUMERIC(20,8) NOT NULL DEFAULT 0,
    range_to                NUMERIC(20,8) NOT NULL DEFAULT 0,
    margin_rate_initial     NUMERIC(18,8) NOT NULL DEFAULT 0,
    margin_rate_maintenance NUMERIC(18,8) NOT NULL DEFAULT 0,

    CONSTRAINT leverage_tiers_rates_positive
        CHECK (margin_rate_initial >= 0 AND margin_rate_maintenance >= 0),
    CONSTRAINT leverage_tiers_range_positive
        CHECK (range_from >= 0 AND range_to >= 0),
    CONSTRAINT leverage_tiers_order UNIQUE (rule_id, range_from)
);

CREATE INDEX IF NOT EXISTS leverage_tiers_rule_id_idx
    ON hst.leverage_tiers (rule_id);

COMMENT ON TABLE hst.leverages IS
    'floating leverage configurations';
COMMENT ON COLUMN hst.leverages."timestamp" IS
    'MT5 change marker, unix nanoseconds; a changed value means a changed record';
COMMENT ON COLUMN hst.leverages.flags IS
    'MT5 Flags, currently not used, carried for parity';

COMMENT ON TABLE hst.leverage_rules IS
    'rules inside a configuration, scoped to a symbol path mask';
COMMENT ON COLUMN hst.leverage_rules.path IS
    'symbol or symbol group mask, for example Forex\*';
COMMENT ON COLUMN hst.leverage_rules.range_mode IS
    'EnRangeMode: 0=RANGE_VOLUME 1=RANGE_VOLUME_PER_SYMBOL 2=RANGE_VALUE 3=RANGE_VALUE_PER_SYMBOL';
COMMENT ON COLUMN hst.leverage_rules.range_value_currency IS
    'currency the notional value is converted to, required when range_mode is 2 or 3';
COMMENT ON COLUMN hst.leverage_rules.config_index IS
    'evaluation order, 0 based; rules match top to bottom and the first match wins';

COMMENT ON TABLE hst.leverage_tiers IS
    'levels within a rule';
COMMENT ON COLUMN hst.leverage_tiers.range_from IS
    'derived by the server from the previous tier range_to, 0 for the first tier';
COMMENT ON COLUMN hst.leverage_tiers.range_to IS
    '0 on the last tier means infinity';
COMMENT ON COLUMN hst.leverage_tiers.margin_rate_maintenance IS
    '0 means no margin charged, NOT fall back to initial';
