-- Server journal: the queryable audit trail behind the Journal tab.
-- The file log in logs/YYYYMMDD.log keeps the same entries, this table is what
-- the back office can filter.

CREATE TABLE IF NOT EXISTS hst.journal (
    journal_id BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at BIGINT       NOT NULL DEFAULT 0,
    type       SMALLINT     NOT NULL DEFAULT 0,
    code       SMALLINT     NOT NULL DEFAULT 0,
    login      BIGINT       NOT NULL DEFAULT 0,
    ip         INET,
    message    VARCHAR(512) NOT NULL DEFAULT '',
    detail     JSONB,

    CONSTRAINT journal_type CHECK (type BETWEEN 0 AND 8),
    CONSTRAINT journal_code CHECK (code BETWEEN 0 AND 4)
);

-- every filter of the journal tab orders by time, so each one is a composite.
-- code has no index: both severity filters are ranges over few distinct values,
-- so the planner walks created_at and filters instead.
CREATE INDEX IF NOT EXISTS journal_created_at_idx
    ON hst.journal (created_at DESC);
CREATE INDEX IF NOT EXISTS journal_login_created_at_idx
    ON hst.journal (login, created_at DESC);
CREATE INDEX IF NOT EXISTS journal_type_created_at_idx
    ON hst.journal (type, created_at DESC);

COMMENT ON TABLE hst.journal IS
    'server journal, append only; one row per audited action';
COMMENT ON COLUMN hst.journal.created_at IS
    'unix nanoseconds';
COMMENT ON COLUMN hst.journal.type IS
    'EnMTLogType: 0=all 1=cfg 2=sys 3=net 4=hst 5=user 6=trade 7=api 8=notify';
COMMENT ON COLUMN hst.journal.code IS
    'severity: 0=ok 1=warn 2=error 3=critical 4=login';
COMMENT ON COLUMN hst.journal.login IS
    'the login that performed the action, 0 when the server did';
COMMENT ON COLUMN hst.journal.ip IS
    'address the action came from, null for server originated entries';
COMMENT ON COLUMN hst.journal.detail IS
    'the structured fields of the entry, for example the record it targeted';
