-- Empty symbol groups the navigator can show before any instrument lives under them.
CREATE TABLE IF NOT EXISTS hst.symbol_folders (
    folder_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    path        VARCHAR(255) NOT NULL,
    updated_at  BIGINT       NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS symbol_folders_path_uidx ON hst.symbol_folders (path);
