package main

import (
	"hstserver/app"

	// docs are generated by the swag CLI, they must be imported for their init
	_ "hstserver/swagger"
)

//	@title			HS Trader
//	@version		1.0
//	@description	HS Trader APIs doc
//	@termsOfService	https://hybridsolutions.com
//	@contact.name	API Support
//	@contact.email	support@hybridsolutions.com
//	@license.url	https://hybridsolutions.com
//	@license.name	HS Trader
//	@BasePath		/
//	@Schemes		http https

//	@securityDefinitions.basic	BasicAuth

//	@securityDefinitions.apikey	BearerAuth
//	@in							header
//	@name						Authorization
//	@description				Type "Bearer" followed by a space and the access token.

func main() {

	app.Start()
}
